name: Bug Report (Form)
description: File a bug report through a simplified form
title: "[MC Version]: "
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form below to describe your issue.
        Keep in mind that this board is **only for issues**! If you have a **suggestion** (ideas, integration etc.), please use the **Discussions** tab instead.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please explain in detail what the issue is. Feel free to attach screenshots or videos, if it helps!
      placeholder: | 
        Example:
        When right-clicking a certain block, the game crashes.
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
      description: Which steps did you take to cause the issue? Please describe below how to replicate it.
      placeholder: |
        Example:
        1. Place block;
        2. Attempt to right click the block.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: | 
        Please provide the client or server logs from your launcher. They contain vital information to troubleshoot the issue.
        To upload logs, you can use websites such as: https://pastebin.com/ https://paste.ee/ https://mclo.gs/
  - type: textarea
    id: mod_list
    attributes:
      label: Mod List
      description: |
        Please provide the list of mods you're using, especially the versions of Forge and Farmer's Delight.
        You can generate a mod list by forcing a crash. In your game, hold F3+C for 10 seconds, then check your logs; the list of mods will be by the end.
    validations:
      required: true
  - type: checkboxes
    id: is_forge
    attributes:
      label: Forge
      description: |
       Please confirm you're playing on the Forge mod loader.
       For issues regarding the Fabric port, go to: https://github.com/newhoryzon/farmers-delight-fabric/issues
      options:
        - label: I am using the Forge version
          required: true
  - type: checkboxes
    id: has_tested_minimal_instance
    attributes:
      label: Minimal instance
      description: Have you tried testing the issue on a Minecraft instance with only Farmer's Delight, and other relevant mods, installed?
      options:
        - label: I have tested this on a minimal instance
  - type: checkboxes
    id: has_performance_mods
    attributes:
      label: Performance and shader mods
      description: Sometimes, performance and shader mods (for example, Optifine, Rubidium etc.) can cause unpredictable problems. Have you tested this issue without those installed?
      options:
        - label: I have tested this without performance or shader mods
