@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package vectorwing.farmersdelight.client.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
