@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package vectorwing.farmersdelight.items.drinks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
